server:
  port: 8080

logging:
  level:
    com.example.dao: DEBUG

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/gp
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  mail:
    host: smtp.163.com
    username: itqiansediao@163.com
    password: 1qaz2wsx
    default-encoding: utf-8
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.example.service

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  #type-aliases-package: com.winter.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

task:
  pool:
    corePoolSize: 5
    maxPoolSize: 10
    keepAliveSeconds: 60
    queueSize: 500
